/**
 * Compiles contracts/FomoMarket.sol and writes lib/artifacts.ts.
 * The ABI the app talks to is therefore always the ABI that was deployed —
 * there is no hand-maintained copy to drift.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import solc from "solc";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = fs.readFileSync(path.join(root, "contracts/FomoMarket.sol"), "utf8");

const out = JSON.parse(solc.compile(JSON.stringify({
  language: "Solidity",
  sources: { "FomoMarket.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
})));

let fatal = false;
for (const e of out.errors ?? []) {
  console.log(e.formattedMessage);
  if (e.severity === "error") fatal = true;
}
if (fatal) process.exit(1);

const C = out.contracts["FomoMarket.sol"];
const pick = (n) => ({ abi: C[n].abi, bytecode: "0x" + C[n].evm.bytecode.object });
const artifacts = { FomoMarket: pick("FomoMarket"), MockUSDG: pick("MockUSDG") };

fs.writeFileSync(
  path.join(root, "lib/artifacts.ts"),
  "// AUTO-GENERATED by scripts/compile.mjs — do not edit.\n" +
  "export const artifacts = " + JSON.stringify(artifacts, null, 2) + " as const;\n",
);

for (const [n, a] of Object.entries(artifacts)) {
  console.log(n, "bytecode", a.bytecode.length / 2 - 1, "bytes");
}
